version: '3.9'
services:
  db:
    image: postgres:17.4
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - sample:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8000:8080'
    links:
      - db

volumes:
  sample: